version: '1.1.0.{build}'

image: Visual Studio 2015

branches:
    only:
    - master

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\directgraph

matrix:
    fast_finish: false
platform:
    - x86
    - x64

configuration:
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14

install:
    - git submodule update --init --recursive
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%
    - cd ..\include
    - python merge_includes.py
    - 7z a ..\directgraph-%PLATFORM%.zip ..\build\directgraph_dx9.dll ..\build\directgraph_dx9.lib directgraph.h

test_script:
    - ctest -C %CONFIGURATION% -LE "dx9" --output-on-failure

artifacts:
    - path: directgraph-*.zip

deploy:
    provider: GitHub
    description: '$(APPVEYOR_REPO_TAG_NAME)'

    auth_token:
        secure: +FpMrNlMtzVMaNzdqZiyDH61Qpd2yi117JElo0HXVX1qZqJEH3ZPBwtsnkw73+m/

    artifact: /directgraph-.*\.zip/
    force_update: true

    on:
        appveyor_repo_tag: true